export const CURRENCY_SYMBOL = "MYR";

import {
  ShoppingCart,
  Utensils,
  Plane,
  Zap,
  Briefcase,
  Dumbbell,
  Banknote,
  Film,
  // New Icons
  Home,
  Car,
  GraduationCap,
  Heart,
  Dog,
  Gift,
  Coffee,
  Smartphone,
  Laptop,
  Shirt,
  Hammer,
  Shield,
  Baby,
  Gamepad2,
  Palette,
  Globe,
  Landmark,
  ReceiptText,
  PiggyBank,
  Truck,
} from "lucide-react";

export const ICONS = [
  { id: "shopping", icon: ShoppingCart },
  { id: "food", icon: Utensils },
  { id: "travel", icon: Plane },
  { id: "utilities", icon: Zap },
  { id: "work", icon: Briefcase },
  { id: "health", icon: Dumbbell },
  { id: "finance", icon: Banknote },
  { id: "entertainment", icon: Film },
  // --- 20 New Icons ---
  { id: "housing", icon: Home },
  { id: "transport", icon: Car },
  { id: "education", icon: GraduationCap },
  { id: "insurance", icon: Shield },
  { id: "wellness", icon: Heart },
  { id: "pets", icon: Dog },
  { id: "gifts", icon: Gift },
  { id: "cafe", icon: Coffee },
  { id: "mobile", icon: Smartphone },
  { id: "tech", icon: Laptop },
  { id: "clothing", icon: Shirt },
  { id: "maintenance", icon: Hammer },
  { id: "family", icon: Baby },
  { id: "gaming", icon: Gamepad2 },
  { id: "hobbies", icon: Palette },
  { id: "subscriptions", icon: ReceiptText },
  { id: "savings", icon: PiggyBank },
  { id: "shipping", icon: Truck },
  { id: "government", icon: Landmark },
  { id: "international", icon: Globe },
];

export const COLORS = [
  { id: "emerald", hex: "bg-cat-emerald" },
  { id: "rose", hex: "bg-cat-rose" },
  { id: "slate", hex: "bg-cat-slate" },
  { id: "maroon", hex: "bg-cat-maroon" },
  { id: "amber", hex: "bg-cat-amber" },
  { id: "indigo", hex: "bg-cat-indigo" },
  { id: "purple", hex: "bg-cat-purple" },
  { id: "cyan", hex: "bg-cat-cyan" },
];
