export const CURRENCY_SYMBOL = "MYR";

import {
  ShoppingCart,
  Utensils,
  Plane,
  Zap,
  Briefcase,
  Dumbbell,
  Banknote,
  Film,
  // New Icons
  Home,
  Car,
  GraduationCap,
  Heart,
  Dog,
  Gift,
  Coffee,
  Smartphone,
  Laptop,
  Shirt,
  Hammer,
  Shield,
  Baby,
  Gamepad2,
  Palette,
  Globe,
  Landmark,
  ReceiptText,
  PiggyBank,
  Truck,
} from "lucide-react";

export const ICONS = [
  { id: "shopping", icon: ShoppingCart },
  { id: "food", icon: Utensils },
  { id: "travel", icon: Plane },
  { id: "utilities", icon: Zap },
  { id: "work", icon: Briefcase },
  { id: "health", icon: Dumbbell },
  { id: "finance", icon: Banknote },
  { id: "entertainment", icon: Film },
  // --- 20 New Icons ---
  { id: "housing", icon: Home },
  { id: "transport", icon: Car },
  { id: "education", icon: GraduationCap },
  { id: "insurance", icon: Shield },
  { id: "wellness", icon: Heart },
  { id: "pets", icon: Dog },
  { id: "gifts", icon: Gift },
  { id: "cafe", icon: Coffee },
  { id: "mobile", icon: Smartphone },
  { id: "tech", icon: Laptop },
  { id: "clothing", icon: Shirt },
  { id: "maintenance", icon: Hammer },
  { id: "family", icon: Baby },
  { id: "gaming", icon: Gamepad2 },
  { id: "hobbies", icon: Palette },
  { id: "subscriptions", icon: ReceiptText },
  { id: "savings", icon: PiggyBank },
  { id: "shipping", icon: Truck },
  { id: "government", icon: Landmark },
  { id: "international", icon: Globe },
];

export const COLORS = [
  { id: "emerald", hex: "bg-cat-emerald", colorHex: "#065f46" },
  { id: "rose", hex: "bg-cat-rose", colorHex: "#be123c" },
  { id: "slate", hex: "bg-cat-slate", colorHex: "#475569" },
  { id: "maroon", hex: "bg-cat-maroon", colorHex: "#991b1b" },
  { id: "amber", hex: "bg-cat-amber", colorHex: "#b45309" },
  { id: "indigo", hex: "bg-cat-indigo", colorHex: "#3730a3" },
  { id: "purple", hex: "bg-cat-purple", colorHex: "#6b21a8" },
  { id: "cyan", hex: "bg-cat-cyan", colorHex: "#0e7490" },
  { id: "blue", hex: "bg-cat-blue", colorHex: "#1d4ed8" },
  { id: "orange", hex: "bg-cat-orange", colorHex: "#ea580c" },
  { id: "teal", hex: "bg-cat-teal", colorHex: "#0d9488" },
  { id: "fuchsia", hex: "bg-cat-fuchsia", colorHex: "#a21caf" },
  { id: "lime", hex: "bg-cat-lime", colorHex: "#4d7c0f" },
  { id: "pink", hex: "bg-cat-pink", colorHex: "#db2777" },
];
